import {
  CHANGE_THEME as CHANGE_THEME_ORIGINAL,
  STORE_THEME as STORE_THEME_ORIGINAL,
  DELETE_THEME as DELETE_THEME_ORIGINAL,
} from 'bootstrap-styled-redux';

export const CHANGE_THEME = CHANGE_THEME_ORIGINAL;
export const STORE_THEME = STORE_THEME_ORIGINAL;
export const DELETE_THEME = DELETE_THEME_ORIGINAL;
