/* Ignored components needed to be used in example */
import BreadcrumbItem from '../src/Breadcrumb/BreadcrumbItem';
import ButtonDropdown from '../src/Button/ButtonDropdown';
import ButtonToolbar from '../src/ButtonGroup/ButtonToolbar';
// import BootstrapProvider from '../src/BootstrapProvider';
// import UtilityProvider from '../src/BootstrapProvider/UtilityProvider';
import CardBlock from '../src/Cards/CardBlock';
import CardBlockquote from '../src/Cards/CardBlockquote';
import CardColumns from '../src/Cards/CardColumns';
import CardDeck from '../src/Cards/CardDeck';
import CardGroup from '../src/Cards/CardGroup';
import CardFooter from '../src/Cards/CardFooter';
import CardHeader from '../src/Cards/CardHeader';
import CardImg from '../src/Cards/CardImg';
import CardImgOverlay from '../src/Cards/CardImgOverlay';
import CardLink from '../src/Cards/CardLink';
import CardSubtitle from '../src/Cards/CardSubtitle';
import CardText from '../src/Cards/CardText';
import CardTitle from '../src/Cards/CardTitle';
import Col from '../src/Col';
import DropdownItem from '../src/Dropdown/DropdownItem';
import DropdownMenu from '../src/Dropdown/DropdownMenu';
import DropdownToggle from '../src/Dropdown/DropdownToggle';
import FaStacked from '../src/Fa/FaStacked';
import FormText from '../src/Form/FormText';
import FormCustom from '../src/Form/FormCustom';
import FormFeedback from '../src/Form/FormFeedback';
import FormGroup from '../src/Form/FormGroup';
import H2 from '../src/H2';
import H3 from '../src/H3';
import H4 from '../src/H4';
import H5 from '../src/H5';
import H6 from '../src/H6';
import FigCaption from '../src/Img/FigCaption';
import Figure from '../src/Img/Figure';
import InputGroupAddon from '../src/InputGroup/InputGroupAddon';
import InputGroupButton from '../src/InputGroup/InputGroupButton';
import Label from '../src/Label';
import ListGroupItem from '../src/ListGroup/ListGroupItem';
import ListGroupItemHeading from '../src/ListGroup/ListGroupItemHeading';
import ListGroupItemText from '../src/ListGroup/ListGroupItemText';
import Fade from '../src/Modal/Fade';
import ModalBody from '../src/Modal/ModalBody';
import ModalFooter from '../src/Modal/ModalFooter';
import ModalHeader from '../src/Modal/ModalHeader';
import NavItem from '../src/Nav/NavItem';
import NavLink from '../src/Nav/NavLink';
import NavbarBrand from '../src/Navbar/NavbarBrand';
import NavbarToggler from '../src/Navbar/NavbarToggler';
import NavDropdown from '../src/Navbar/NavDropdown';
import Option from '../src/Option';
import Output from '../src/Output';
import PaginationItem from '../src/Pagination/PaginationItem';
import PaginationLink from '../src/Pagination/PaginationLink';
import ProgressBar from '../src/Progress/ProgressBar';
import Section from '../src/Section';
import Tbody from '../src/Table/Tbody';
import Td from '../src/Table/Td';
import Tfoot from '../src/Table/Tfoot';
import Th from '../src/Table/Th';
import Thead from '../src/Table/Thead';
import Tr from '../src/Table/Tr';
import TetherContent from '../src/TetherContent';

global.BreadcrumbItem = BreadcrumbItem;
global.ButtonDropdown = ButtonDropdown;
global.ButtonToolbar = ButtonToolbar;
// global.BootstrapProvider = BootstrapProvider;
// global.UtilityProvider = UtilityProvider;
global.CardBlock = CardBlock;
global.CardBlockquote = CardBlockquote;
global.CardColumns = CardColumns;
global.CardDeck = CardDeck;
global.CardGroup = CardGroup;
global.CardFooter = CardFooter;
global.CardHeader = CardHeader;
global.CardImg = CardImg;
global.CardImgOverlay = CardImgOverlay;
global.CardLink = CardLink;
global.CardSubtitle = CardSubtitle;
global.CardText = CardText;
global.CardTitle = CardTitle;
global.Col = Col;
global.DropdownItem = DropdownItem;
global.DropdownMenu = DropdownMenu;
global.DropdownToggle = DropdownToggle;
global.FaStacked = FaStacked;
global.FormText = FormText;
global.FormCustom = FormCustom;
global.FormFeedback = FormFeedback;
global.FormGroup = FormGroup;
global.H2 = H2;
global.H3 = H3;
global.H4 = H4;
global.H5 = H5;
global.H6 = H6;
global.FigCaption = FigCaption;
global.Figure = Figure;
global.InputGroupAddon = InputGroupAddon;
global.InputGroupButton = InputGroupButton;
global.Label = Label;
global.ListGroupItem = ListGroupItem;
global.ListGroupItemHeading = ListGroupItemHeading;
global.ListGroupItemText = ListGroupItemText;
global.Fade = Fade;
global.ModalBody = ModalBody;
global.ModalFooter = ModalFooter;
global.ModalHeader = ModalHeader;
global.NavItem = NavItem;
global.NavLink = NavLink;
global.NavbarBrand = NavbarBrand;
global.NavbarToggler = NavbarToggler;
global.NavDropdown = NavDropdown;
global.Option = Option;
global.Output = Output;
global.PaginationItem = PaginationItem;
global.PaginationLink = PaginationLink;
global.ProgressBar = ProgressBar;
global.Section = Section;
global.Tbody = Tbody;
global.Td = Td;
global.Tfoot = Tfoot;
global.Thead = Thead;
global.Th = Th;
global.Tr = Tr;
global.TetherContent = TetherContent;
